;METADATA=(Diff=true, UseCommands=true)
[/Script/GameplayTags.GameplayTagsSettings]
ImportTagsFromConfig=True
WarnOnInvalidTags=True
ClearInvalidTags=False
AllowEditorTagUnloading=True
AllowGameTagUnloading=False
FastReplication=False
bDynamicReplication=False
InvalidTagCharacters="\"\',"
NumBitsForContainerSize=6
NetIndexFirstBitSegment=16
+GameplayTagList=(Tag="Attributes.Vital.Health",DevComment="Keeps track of an entity\'s health.")
+GameplayTagList=(Tag="Attributes.Vital.Mana",DevComment="How much mana this entity has (to cast spells)")
+GameplayTagList=(Tag="Event.Montage.FireBolt",DevComment="")
+GameplayTagList=(Tag="Message.HealthCrystal",DevComment="Displayed when consuming a health crystal")
+GameplayTagList=(Tag="Message.HealthPotion",DevComment="Displayed when consuming a health potion")
+GameplayTagList=(Tag="Message.ManaCrystal",DevComment="Displayed when consuming a mana crystal")
+GameplayTagList=(Tag="Message.ManaPotion",DevComment="Displayed when consuming a mana potion")

